# Generated by Django 5.1.6 on 2025-05-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_enrollment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='instructed_courses', through='app.TeachingAssignment', to='app.course'),
        ),
    ]
