# Generated by Django 5.1.6 on 2025-05-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_teachingassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learned_skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
