# Generated by Django 5.1.6 on 2025-05-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
