# Generated by Django 5.1.6 on 2025-05-25 04:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_course_learned_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True),
        ),
    ]
