# Generated by Django 5.1.6 on 2025-05-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user_self_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_instructor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Học viên'), ('instructor', 'Giảng viên'), ('admin', 'Quản trị viên')], default='student', max_length=20),
        ),
    ]
