# Generated by Django 5.1.6 on 2025-05-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_blogcomment_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('instructor', 'instructor'), ('admin', 'admin')], default='student', max_length=20),
        ),
    ]
