# Generated by Django 5.1.6 on 2025-05-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_video_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
