# Generated by Django 5.1.6 on 2025-05-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_course_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Lesson',
        ),
    ]
