# Generated by Django 5.1.6 on 2025-05-27 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_video_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='video',
            new_name='lesson',
        ),
    ]
